# -*- coding: utf-8 -*-
"""unique_mmsi_data_to_all_mmsi.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JEPIB4Dhf7gdSuInes6z0PPyGdC7wpNv
"""

# importing module
from pandas import *
 
# reading CSV file
data = read_csv("unique_mmsi_csv.csv")
 
# converting column data to list
unique_mmsi = data['mmsi'].tolist()

# reading CSV file
data1 = read_csv("all_mmsi_csv.csv")
 
# converting column data to list
all_mmsi = data1['mmsi'].tolist()

print(len(all_mmsi))
print(len(unique_mmsi))

count = 0

for x in all_mmsi:
  temp = unique_mmsi.index(x)
  data1['score'][count] = data['score'][temp]
  data1['flag'][count] = data['flag'][temp]
  data1['gear type'][count] = data['gear type'][temp]
  data1['vessel type'][count] = data['vessel type'][temp]
  print(count)
  count = count + 1

import pandas as pd

df1 = pd.DataFrame(data1)
df1.to_csv('all_mmsi_final.csv', index=False)